# Generated by Django 5.1.4 on 2024-12-11 20:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('instructional_items', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(64)])),
                ('assessment_items', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(64)])),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='course.course')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id_course', 'order'), name='unique_order_per_course')],
            },
        ),
    ]
