# Generated by Django 5.1.3 on 2024-12-01 18:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_category', '0001_initial'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('creation_date', models.DateField()),
                ('last_update', models.DateField()),
                ('modules_count', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_category.coursecategory')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution')),
            ],
        ),
    ]
