# Generated by Django 5.1.3 on 2024-11-26 03:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('visibility', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('creation_date', models.DateField()),
            ],
        ),
    ]
