# Generated by Django 5.1.4 on 2024-12-11 19:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_category', '0001_initial'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('alias', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Alias must contain only lowercase letters, numbers, underscores (_), or hyphens (-), without spaces.', regex='^[a-z0-9_-]+$')])),
                ('active', models.BooleanField(blank=True, default=False)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_update', models.DateField(auto_now=True)),
                ('modules', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('assessment_items', models.PositiveIntegerField(blank=True, default=0)),
                ('reviews', models.PositiveIntegerField(blank=True, default=0)),
                ('comments', models.PositiveIntegerField(blank=True, default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_category.coursecategory')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution')),
            ],
        ),
    ]
