# Generated by Django 5.1.5 on 2025-02-13 23:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_category', '0001_initial'),
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('reviews', models.PositiveIntegerField(blank=True, default=0)),
                ('comments', models.PositiveIntegerField(blank=True, default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content_category.contentcategory')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='module.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
